services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
  client-gateway:
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
  products-microservice:
    build: ./products-microservice
    volumes:
      - ./products-microservice/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3001
      - DATABASE_URL=file:./prisma/dev.db
      - NATS_SERVERS= nats://nats-server:4222
  orders-microservice:
    depends_on:
      - orders-db
    build: ./orders-microservice
    volumes:
      - ./orders-microservice/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:admin@orders-db:5432/orders_db?schema=public
      - NATS_SERVERS= nats://nats-server:4222
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - orders_ms_pg:/var/lib/postgresql/data
    ports:
      - 5480:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=orders_db
volumes:
  orders_ms_pg: